name: Set up Ruby
description: Sets up Ruby environment and installs Ruby
runs:
  using: composite
  steps:
    - name: Setup ruby env.
      shell: bash
      run: |
        sudo apt-get update;
        sudo apt-get install --reinstall -y locales;
        sudo sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen;
        sudo locale-gen en_US.UTF-8;

    - name: Install ruby.
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
