name: Set up JavaScript
description: Installs node and npm dependencies
runs:
  using: composite
  steps:
    - name: Install node.js.
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install NPM dependencies.
      run: npm install
