name: Accessibility scan

on:
  - pull_request

jobs:
  build:
    name: pa11y-ci
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LANGUAGE: en_US
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup-ruby

      - uses: ./.github/actions/setup-js

      - name: Build and start up jekyll server.
        run: npm run build && npm run start-detached

      - name: Run pa11y-ci.
        run: npm run pa11y-ci:sitemap
